services:
  app:
    image: bitnami/laravel
    volumes:
      - ./laravel:/app
    working_dir: /app
    command: >
      bash -c "composer install && php artisan serve --host 0.0.0.0 --port 8000"
    ports:
    - 8000:8000
    depends_on:
      - elastic
    networks:
      - app-network

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elastic
    hostname: elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - app-network

volumes:
  es_data:
    driver: local

networks:
  app-network:
    driver: bridge